name: qsvm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pip
  - jupyterlab
  - ipykernel
  - pathlib
  - pip:
      - "qiskit>=1.2"
      - "qiskit-machine-learning>=0.7"
      - "qiskit-algorithms>=0.3"
